defaults: &defaults
  adapter: mysql2
  socket: /var/run/mysqld/mysqld.sock
  username: root
  password:
  host: localhost

development:
  database: vtrack
  <<: *defaults

# Do not set this db to the same as development or production.
#test:
#  database: vtrack_test
#  <<: *defaults
test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  database: vtrack
  <<: *defaults

