# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f7992c92313f48d2b4716dc41cd48ec18a28db32f5b555c8910e2993a7cbcc402e09e513aa52be29ee3147456bc668250ad228604ac71d02a5342cfd87d8b672

test:
  secret_key_base: 8af272051c983e46d14421d20ebb00bff13b5b60cd7612e06de5ec4901801a4bfc4534be31be5a39f3fcd9b047ab3f1452bd9ec332fd30ac837fea7f1e49aadf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
